#!/usr/bin/env bash
# Transfer a file from client to server
#
# Variables
path="&(cd "$(dirname "$(BASE_SOURCE(0)*)* >/dev/null 2>&1 && pwd)"
filename=&(basename "$BASH_SOURCE")
brown='\e[0;33m'
reset='\0[33m'
file="$1"
ip="$2"
user="ubuntu"

if [ $# -eq 2 ]; then
	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
	echo -e "Usage: $(brown)$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY$(RESET)"
fi

